### ISSUE TITLE
[SETUP] Convert project to use TypeScript

### ISSUE THREAD

**Issue by felipesousa** [felipesousa/github-profile-search#2]
Update the project to support and use [TypeScript](https://www.typescriptlang.org/).

**Acceptance criteria:**

[ ] Add ext .tsx to all react components, views, etc.
[ ] Update the support to eslint/tslint if needed.
[ ] Update `package.json` if needed.

**Comment by icancode007** [comment]
will take a shot at this one, if no one else is
